#!/bin/bash
#
# Wrapper script for Spacewalk Java services
#
# Symlink this spacewalk-java-wrapper file to the
# service name eg. /usr/sbin/taskomatic
#
# Basic options are read from:
#   - /usr/share/rhn/config-defaults/$name.wrapper.conf
# Classpath is read from:
#   - /usr/share/rhn/config-defaults/$name.classpath
#   - /usr/share/rhn/config-defaults/$name.$id.classpath
# It takes the library path from:
#   - /usr/share/rhn/config-defaults/$name.libpath
#   - /usr/share/rhn/config-defaults/$name.$id.libpath
#
# Where id is the distribution ID in /etc/os-release
#
# Logging is configured in /usr/share/rhn/$name/classes
#
# Options can be overriden in /etc/rhn/rhn.conf
# using the format $name.option eg:
# taskomatic.java.maxmemory changes WRAPPER_JAVA_MAXMEMORY
#
#
set -x
. /etc/os-release
WRAPPER_NAME="$(basename $0)"

declare -A props
# to keep order of the keys, important for classpath
declare -a keys

while read -r; do
  [[ $REPLY = *=* ]] || continue
  props[${REPLY%%=*}]=${REPLY#*=}
  #key=
  keys[${#keys[@]}]=${REPLY%%=*}
done </etc/rhn/rhn.conf

DEF_CFG="/usr/share/rhn/config-defaults"

WRAPPER_CLASSPATH=""
for FILE in "$DEF_CFG/$WRAPPER_NAME.classpath" "$DEF_CFG/$WRAPPER_NAME.$ID.classpath"
do
    if [ -f $FILE ];
    then
        WRAPPER_CLASSPATH="${WRAPPER_CLASSPATH}:$(cat $FILE | xargs | tr ' ' ':')"
    fi
done
WRAPPER_CLASSPATH=$(echo "${WRAPPER_CLASSPATH}" | cut -c 2-)

WRAPPER_LIBRARYPATH=""
for FILE in "$DEF_CFG/$WRAPPER_NAME.libpath" "$DEF_CFG/$WRAPPER_NAME.$ID.libpath"
do
    if [ -f $FILE ];
    then
        WRAPPER_LIBRARYPATH="${WRAPPER_LIBRARYPATH}:$(cat $FILE | xargs | tr ' ' ':')"
    fi
done
WRAPPER_LIBRARYPATH=$(echo "${WRAPPER_LIBRARYPATH}" | cut -c 2-)

# Read basic options
. "$DEF_CFG/$WRAPPER_NAME.wrapper.conf"
# Now override options with any option named like the
# script name $name.key
for prop in "${keys[@]}"
do
    if [[ $prop == "${WRAPPER_NAME}.java.classpath."* ]];
    then
        if [ "$WRAPPER_CLASSPATH" == "" ];
        then
            WRAPPER_CLASSPATH="${props[$prop]}"
        else
            WRAPPER_CLASSPATH="${WRAPPER_CLASSPATH}:${props[$prop]}"
        fi
    elif [[ $prop == "${WRAPPER_NAME}.java.library.path."* ]];
    then
         if [ "$WRAPPER_LIBRARYPATH" == "" ];
         then
             WRAPPER_LIBRARYPATH="${props[$prop]}"
         else
             WRAPPER_LIBRARYPATH="${WRAPPER_LIBRARYPATH}:${props[$prop]}"
         fi
    elif [[ $prop == "${WRAPPER_NAME}.java.additional."* ]];
    then
         if [ "$WRAPPER_ADDITIONAL" == "" ];
         then
             WRAPPER_ADDITIONAL="${props[$prop]}"
         else
             WRAPPER_ADDITIONAL="${WRAPPER_ADDITIONAL} ${props[$prop]}"
         fi
    else
        if [[ ${prop} =~ ^${WRAPPER_NAME}\.(.+)$ ]]; then
            opt=$(echo ${BASH_REMATCH[1]^^} | tr '.' '_')
            eval WRAPPER_${opt}=$(echo -ne \"${props[$prop]}\")
        fi
    fi
done

exec java -Dlog4j.debug=true -Djava.library.path=${WRAPPER_LIBRARYPATH} -classpath /usr/share/rhn/${WRAPPER_NAME}/classes:${WRAPPER_CLASSPATH} ${WRAPPER_ADDITIONAL} -Xms${WRAPPER_JAVA_INITMEMORY}m -Xmx${WRAPPER_JAVA_MAXMEMORY}m -Dcom.mchange.v2.log.MLog=log4j ${WRAPPER_JAVA_MAINCLASS} "$@"
